=== cesarRDH24/ordinario-ftw/xml/musica.dtd
<!ELEMENT musicahub (artista+)>

<!ELEMENT artista (nombre,pais,genero,album,cancion)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT cancion (#PCDATA)>

=== cesarRDH24/ordinario-ftw/xml/musica.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE musicahub SYSTEM "musica.dtd">

<musicahub>

    <artista>
        <nombre>Radiohead</nombre>
        <pais>Reino Unido</pais>
        <genero>Alternative Rock</genero>
    </artista>

    <artista>
        <nombre>The Strokes</nombre>
        <pais>Estados Unidos</pais>
        <genero>Indie Rock</genero>
    </artista>

    <artista>
        <nombre>Arctic Monkeys</nombre>
        <pais>Reino Unido</pais>
        <genero>Indie Rock</genero>
    </artista>

    <artista>
        <nombre>Tame Impala</nombre>
        <pais>Australia</pais>
        <genero>Psychedelic Rock</genero>
    </artista>

    <artista>
        <nombre>Daft Punk</nombre>
        <pais>Francia</pais>
        <genero>Electronic</genero>
    </artista>

</musicahub>
